version: '3.8'

services:
  db:
    container_name: mysql-container
    image: mysql:5.7
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    env_file:
      - ./.env.dev
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=user
      - MYSQL_PASSWORD=toor
      - MYSQL_DATABASE=pokedex
    ports:
      - "3306:3306"

  web:
    container_name: django-web
    build:
      context: ./pokedex_project
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8042
    volumes:
      - ./pokedex_project:/app
    ports:
      - "8042:8042"
    depends_on:
      - db
    links:
      - db
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=amine123
